#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child

# Opacity
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.5

# Shadow
yabai -m config window_shadow                on

# Split & Balance
yabai -m config split_ratio                  0.6
yabai -m config auto_balance                 off

# Mouse
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# yabai -m config mouse_follows_focus          on


# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5 
yabai -m config window_gap                   5

# ignore some apps
yabai -m rule --add app="Ghostty" manage=off
yabai -m rule --add app="iTerm2" manage=off

echo "yabai configuration loaded.."s
