#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmot                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.5
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config split_ratio                  0.55
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config native-fullscreen            off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding 		     10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10 
yabai -m config window_gap                   10

# ignore some apps

yabai -m rule --add app="Loom" sticky=on layer=above manage=off
yabai -m rule --add app="iTerm2" sticky=on layer=above manage=off


echo "yabai configuration loaded.."s
